services:
  category:
    build: category
  purchase:
    build: purchase
    depends_on:
      - category
    environment:
      - CATEGORY_SERVER=category:8000
  frontend:
    build: frontend
    depends_on:
      - category
      - purchase
    environment:
      - CATEGORY_SERVER=category:8000
      - PURCHASE_SERVER=purchase:4567
      - PORT=3000
    ports:
      - 3000:3000
    